# Sistemas lineares

$$x_{1}{\begin{bmatrix}a_{11}\\a_{21}\\\vdots \\a_{m1}\end{bmatrix}}+x_{2}{\begin{bmatrix}a_{12}\\a_{22}\\\vdots \\a_{m2}\end{bmatrix}}+\cdots +x_{n}{\begin{bmatrix}a_{1n}\\a_{2n}\\\vdots \\a_{mn}\end{bmatrix}}={\begin{bmatrix}b_{1}\\b_{2}\\\vdots \\b_{m}\end{bmatrix}}$$


$$A={\begin{bmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mn}\end{bmatrix}},\quad {\mathbf {x}}={\begin{bmatrix}x_{1}\\x_{2}\\\vdots \\x_{n}\end{bmatrix}},\quad {\mathbf {b}}={\begin{bmatrix}b_{1}\\b_{2}\\\vdots \\b_{m}\end{bmatrix}}$$

ou em notação matricial:

$$A{\mathbf {x}} = {\mathbf {b}}$$

In [1]:
import numpy as np

A = np.array([[2,1,4,1],
             [3,4,-1,-1],
             [1,-4,1,5],
             [2,-2,1,3]],float)

v = np.array([-4,3,9,7],float)
N = len(v)

# Eliminação de Gauss

for m in range(N):
    
    #divide pelo elemento da diagonal
    div = A[m,m]
    A[m,:] = A[m,:]/div
    v[m] = v[m]/div
    
    # subtrair das linhas seguintes
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] = A[i,:] - mult*A[m,:]
        v[i] = v[i] - mult*v[m]
        
        print '---------------------------'
        print A
        print v
        print ''
        
# recorrencia para obter solução

x = np.zeros(N,float)

for m in range(N-1,-1,-1):
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] = x[m] - A[m,i]*x[i]
        
print "a solução é: ", x

# usando os modulos do numpy

print np.linalg.solve(A,v)
print ''
print "a solução com modulo solve é: ", x

---------------------------
[[ 1.   0.5  2.   0.5]
 [ 0.   2.5 -7.  -2.5]
 [ 1.  -4.   1.   5. ]
 [ 2.  -2.   1.   3. ]]
[-2.  9.  9.  7.]

---------------------------
[[ 1.   0.5  2.   0.5]
 [ 0.   2.5 -7.  -2.5]
 [ 0.  -4.5 -1.   4.5]
 [ 2.  -2.   1.   3. ]]
[ -2.   9.  11.   7.]

---------------------------
[[ 1.   0.5  2.   0.5]
 [ 0.   2.5 -7.  -2.5]
 [ 0.  -4.5 -1.   4.5]
 [ 0.  -3.  -3.   2. ]]
[ -2.   9.  11.  11.]

---------------------------
[[  1.    0.5   2.    0.5]
 [  0.    1.   -2.8  -1. ]
 [  0.    0.  -13.6   0. ]
 [  0.   -3.   -3.    2. ]]
[ -2.    3.6  27.2  11. ]

---------------------------
[[  1.    0.5   2.    0.5]
 [  0.    1.   -2.8  -1. ]
 [  0.    0.  -13.6   0. ]
 [  0.    0.  -11.4  -1. ]]
[ -2.    3.6  27.2  21.8]

---------------------------
[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [ 0.   0.   0.  -1. ]]
[-2.   3.6 -2.  -1. ]

a solução é:  [ 2. -1. -2.  1.]
[ 2. -1. -2.  1.]

a solução com modulo solve é:  [ 2. -1. -2.  1.]


In [8]:
print A

[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [-0.  -0.  -0.   1. ]]


In [20]:
print "%10.20f"% A[2,0]

-0.00000000000000000000
