# Sistemas lineares

Um sistema linear é um conjunto de duas ou mais equações lineares envolvendo as mesmas variáveis.

Por exemplo:

$${\begin{alignedat}{7}3x&&\;+\;&&2y&&\;-\;&&z&&\;=\;&&1&\\2x&&\;-\;&&2y&&\;+\;&&4z&&\;=\;&&-2&\\-x&&\;+\;&&{\tfrac {1}{2}}y&&\;-\;&&z&&\;=\;&&0&\end{alignedat}}$$

A solução para este sistema é:

$$ {\begin{alignedat}{2}x&\,=\,&1\\y&\,=\,&-2\\z&\,=\,&-2\end{alignedat}} $$

que satisfaz a todas as equações simultaneamente. A algebra linear é o campo da matemática que estuda estes sistemas.

Na sua forma geral temos:


$$ {\displaystyle {\begin{aligned}a_{11}x_{1}&+a_{12}x_{2}+\cdots +a_{1n}x_{n}=b_{1}\\a_{21}x_{1}&+a_{22}x_{2}+\cdots +a_{2n}x_{n}=b_{2}\\\vdots &\\a_{m1}x_{1}&+a_{m2}x_{2}+\cdots +a_{mn}x_{n}=b_{m},\end{aligned}}} $$

Usando notação vetorial também pode-se escrever:


$$x_{1}{\begin{bmatrix}a_{11}\\a_{21}\\\vdots \\a_{m1}\end{bmatrix}}+x_{2}{\begin{bmatrix}a_{12}\\a_{22}\\\vdots \\a_{m2}\end{bmatrix}}+\cdots +x_{n}{\begin{bmatrix}a_{1n}\\a_{2n}\\\vdots \\a_{mn}\end{bmatrix}}={\begin{bmatrix}b_{1}\\b_{2}\\\vdots \\b_{m}\end{bmatrix}}$$


ou em notação matricial:

$$A{\mathbf {x}} = {\mathbf {b}}$$

$$A={\begin{bmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mn}\end{bmatrix}},\quad {\mathbf {x}}={\begin{bmatrix}x_{1}\\x_{2}\\\vdots \\x_{n}\end{bmatrix}},\quad {\mathbf {b}}={\begin{bmatrix}b_{1}\\b_{2}\\\vdots \\b_{m}\end{bmatrix}}$$

A notação matricial é util e nos mostra que a solução pode ser obtida de:

$${\mathbf {x}} = A^{-1}{\mathbf {b}}$$

ou seja, através da obtenção da matriz inversa de $A$. No entanto, computacionalmente, inversão de matrizes é uma operação em geral custosa e ineficiente.

Para uma discussão dos tipos de sistemas assim como alguns métodos de solução veja:

https://en.wikipedia.org/wiki/System_of_linear_equations

## Método de eliminação de Gauss

Consiste basicamente na obtenção da matriz escalonada de A a partir de operações elementares.

A matriz escalonada tem a forma:

$$\left[{\begin{array}{rrrr}2&-3&2&1\\0&1&-4&8\\0&0&0&35\end{array}}\right]$$

As operações básicas que podem ser aplicadas a matriz, sem alterar a solução são:

- Somar a uma linha um múltiplo de outra linha.
- Trocar duas linhas entre si.
- Multiplicar todos os elementos de uma linha por uma constante não-nula.

Para uma aplicação passo a passo do método veja:

https://pt.wikipedia.org/wiki/Elimina%C3%A7%C3%A3o_de_Gauss

O Numpy e o Scipy tem pacotes específicos para a solução de sistemas lineares. 

A função usada é a solve (https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.solve.html) que se encontra no pacote de funções de algebra linear do Numpy. O pacote de algebra linear do numpy contém inumeras funções para realização de operações com vetores e matrizes. Para uma lista e exemplos veja:

https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html

O pacote Scipy também contém um pacote de funções para realizar operações com algebra linear. Algumas funções adicionais como a decomposição LU podem ser encontradas aqui:

https://docs.scipy.org/doc/scipy-0.14.0/reference/linalg.html


In [5]:
import numpy as np

A = np.array([[2,1,4,1],
             [3,4,-1,-1],
             [1,-4,1,5],
             [2,-2,1,3]],float)

v = np.array([-4,3,9,7],float)
N = len(v)

# Eliminação de Gauss

for m in range(N):
    
    #divide pelo elemento da diagonal
    div = A[m,m]
    A[m,:] = A[m,:]/div
    v[m] = v[m]/div
    
    # subtrair das linhas seguintes
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] = A[i,:] - mult*A[m,:]
        v[i] = v[i] - mult*v[m]
        
        print '---------------------------'
        print A
        print v
        print ''
        
# recorrencia para obter solução

x = np.zeros(N,float)

for m in range(N-1,-1,-1):
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] = x[m] - A[m,i]*x[i]
        
print "a solução é: ", x

# usando os modulos do numpy

print np.linalg.solve(A,v)
print ''
print "a solução com modulo solve é: ", x

---------------------------
[[ 1.   0.5  2.   0.5]
 [ 0.   2.5 -7.  -2.5]
 [ 1.  -4.   1.   5. ]
 [ 2.  -2.   1.   3. ]]
[-2.  9.  9.  7.]

---------------------------
[[ 1.   0.5  2.   0.5]
 [ 0.   2.5 -7.  -2.5]
 [ 0.  -4.5 -1.   4.5]
 [ 2.  -2.   1.   3. ]]
[ -2.   9.  11.   7.]

---------------------------
[[ 1.   0.5  2.   0.5]
 [ 0.   2.5 -7.  -2.5]
 [ 0.  -4.5 -1.   4.5]
 [ 0.  -3.  -3.   2. ]]
[ -2.   9.  11.  11.]

---------------------------
[[  1.    0.5   2.    0.5]
 [  0.    1.   -2.8  -1. ]
 [  0.    0.  -13.6   0. ]
 [  0.   -3.   -3.    2. ]]
[ -2.    3.6  27.2  11. ]

---------------------------
[[  1.    0.5   2.    0.5]
 [  0.    1.   -2.8  -1. ]
 [  0.    0.  -13.6   0. ]
 [  0.    0.  -11.4  -1. ]]
[ -2.    3.6  27.2  21.8]

---------------------------
[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [ 0.   0.   0.  -1. ]]
[-2.   3.6 -2.  -1. ]

a solução é:  [ 2. -1. -2.  1.]
[ 2. -1. -2.  1.]

a solução com modulo solve é:  [ 2. -1. -2.  1.]


In [8]:
#Solução de sistemas lineares usando Scipy e decomposição LU

import scipy.linalg as linalg 
import numpy as np 

#define A 
A = np.array([[2., 1., 1.], [1., 3., 2.], [1., 0., 0.]]) 
#define B 
B = np.array([4., 5., 6.]) 

#call the lu_factor function 
LU = linalg.lu_factor(A) 

#solve given LU and B 
x = linalg.lu_solve(LU, B) 

print "Solutions:\n",x 
print ' '

# vamos ver o que foi feito com a matriz original
P, L, U = linalg.lu(A) 
print P 
print ' '
print L 
print ' '
print U 


Solutions:
[  6.  15. -23.]
 
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
 
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.5 -0.2  1. ]]
 
[[ 2.   1.   1. ]
 [ 0.   2.5  1.5]
 [ 0.   0.  -0.2]]


In [7]:
print "%10.20f"% A[2,0]

1.00000000000000000000
